# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 407853a976d3a3746b0178f22c3874bc99748a860c6cc1794c21f8f7861e34259b25601d262cc098ab9aa701a321fab02e350be83ee1b3cb48eb1cc9c60d80ef
  FB_APP_ID: '458806257617475'
  FB_APP_SECRET: '4a2128916abb5535ac4fde3727ef1f35'
test:
  secret_key_base: 9f5f0ee990d46c137c7831306a81c9a4ba93d1166245ac74113233dd90be70ed949a1c829a85413a19951b28349483979ccf1a957bb313e767ba90cd1a5ae353
  FB_APP_ID: '458806257617475'
  FB_APP_SECRET: '4a2128916abb5535ac4fde3727ef1f35'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FB_APP_ID: <%= ENV["FB_APP_ID"] %>
  FB_APP_SECRET: <%= ENV["FB_APP_SECRET"] %>